spring:
  datasource:
    url: jdbc:mysql://localhost:3306/schooldb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: rootuser
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true